export enum apis {
  LOGIN = 'auth/agent-login',
  REFRESH_TOKEN = 'auth/refresh-token',
  CHANGE_PASSWORD = 'agents/change-password',
  DISPLAY_PICTURE = 'uploads/agents/display-picture',
  PROFILE = 'agents/profile',
  FCM_TOKEN = 'agents/sync-fcm-token',
  METRICS = 'agents/metrics',
  TRENDING = 'agents/trendings',
  SYNC_LOCATION = 'agents/sync-location',
  VERIFICATION = 'agents/verifications',
  ACCEPT_TASK = 'agents/accept-task',
  SINGLE_ADDRESS = 'agents/addresses/',
  UPDATE_ADDRESS = 'agents/update-address',
  SUBMIT_ADDESS = 'agents/submit',
  UPDATE_ADDRESS_STATUS = 'agents/update-status',
  UPLOAD_IMAGE = 'uploads/agents/images',
  UPLOAD_SIGNATURE = 'uploads/agents/signatures',
  UPLOAD_AUDIO = 'uploads/address/audio',
}
